### ISSUE TITLE
Always say there is a new version and try to update. 

### ISSUE THREAD

**Issue by JKAUSHALYA** [prabath/wso2is-repo-explorer#2]
Whenever ran the command ./rex.sh following message will appear and try to download the latest docker images.
`There is an updated Docker image available...`

This seems related to the following issue. https://github.com/prabath/wso2is-repo-explorer/issues/1

I can see the following error message. 
`rm: cannot remove '.repodata/image.update': Permission denied`

**Comment by prabath** [comment]
This is related to https://github.com/prabath/wso2is-repo-explorer/issues/1
